name: test in ubuntu

on:
  push:
    branches: master
  pull_request:
    branches: master

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: init env
        run: mkdir target

      - name: building
        working-directory: target
        run:
          cpu=$(cat /proc/cpuinfo | grep processor|wc -l) &&
          echo "processor num is ${cpu}"  &&
          cmake .. && make -j${cpu} \
      - name: test
        working-directory: target
        run: make test